controller:
  kind: DaemonSet

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  daemonset:
    useHostPort: true

  service:
    type: ClusterIP

  admissionWebhooks:
    enabled: false

  metrics:
    enabled: true
